#!/usr/bin/env bash
# transfer files using arguments
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
scp StrictHostKeyChecking=no "$1" "$3"@"$2":~/ -i "$4"
