#!/usr/bin/env bash
#installing and set up nginx 
sudo apt-get update -y
sudo apt-get install nginx -y

sudo servise nginx start
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html


sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=87SH2Cn0s9A&t=3210s&ab_channel=BroCode permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" >> /var/www/html/error_404.html

sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
