#!/usr/bin/env bash
# debugging some web stack issues
apt install -y nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
