#!/usr/bin/env bash
#print bad luck for 4 and good luck for 8
i=1
while [ $i -lt 11 ]
do
if [ $i -eq 4 ]
then
echo bad luck
i=$((i + 1))
elif [ $i -eq 8 ]
then
echo good luck
i=$((i + 1))
else
echo Best School
i=$((i + 1))
fi
done
